# Generated by Django 4.0.4 on 2022-05-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
